### ISSUE TITLE
In install space, cannot find libraries

### ISSUE THREAD

**Issue by jonbinney** [ros-drivers/openni2_camera#10]
To replicate, download the sources, then do a

``` bash
catkin_make install
. install/setup.bash
rosrun openni2_camera openni2_camera_node
```

The output is:

``` bash
terminate called after throwing an instance of 'openni2_wrapper::OpenNI2Exception'
  what():  openni2_wrapper::OpenNI2DeviceManager::OpenNI2DeviceManager() @ /wg/stor5/jbinney/ws/openni2_camera/src/openni2_camera/src/openni
2_device_manager.cpp @ 185 : Initialize failed
        LibraryHandler: Couldn't load library libDummyDevice.so.0
        DeviceDriver: library handle is invalid for file libDummyDevice.so.0
        Couldn't understand file 'libDummyDevice.so.0' as a device driver
        LibraryHandler: Couldn't load library libOniFile.so.0
        DeviceDriver: library handle is invalid for file libOniFile.so.0
        Couldn't understand file 'libOniFile.so.0' as a device driver
        LibraryHandler: Couldn't load library libPS1080.so.0
        DeviceDriver: library handle is invalid for file libPS1080.so.0
        Couldn't understand file 'libPS1080.so.0' as a device driver
        Found no valid drivers in '/usr/lib/OpenNI2/Drivers'
```

This appears to be because the libopenni2-0 library puts the libraries for each device driver in /usr/lib/OpenNI2/Drivers, but doesn't add that to the library search path in /etc/ld.so.conf. This doesn't fail in devel space because we get the library path for OpenNI2 from package config:

``` bash
jbinney@jbk-> pkg-config --libs libopenni2
-L/usr/lib/OpenNI2/Drivers -lOpenNI2 -lDummyDevice -lOniFile -lPS1080.so
```

Possible solution would be to have libopenni2-0 install a file into /etc/ld.so.conf.d/ to add /usr/lib/OpenNI2/Drivers to the library search path, so this is probably actually a bug with that library and not with openni2_camera. But I'm leaving this here because it is blocking the release of this package.

**Comment by jonbinney** [comment]
Created an issue for this on the OpenNI2 repo: https://github.com/hcw70/OpenNI2/issues/12

**Comment by hcw70** [comment]
@jonbinney Please note that https://github.com/hcw70/OpenNI2 is not "the OpenNI2 repo" but a fork of the repo plus debian packaging and raspberry-pi fixes.

**Comment by jonbinney** [comment]
Oops, yeah I mean the repo that the ROS debs for OpenNI2 get released from, since that is what an installed version of openn2_camera will need to work with.

**Comment by wjwwood** [comment]
I get this on OS X:

```
[ERROR] [1376608025.175700000]: Exception thrown while processing service call: openni2_wrapper::OpenNI2DeviceManager::OpenNI2DeviceManager() @ /tmp/pcl_ws/src/openni2_camera/src/openni2_device_manager.cpp @ 185 : Initialize failed
    Found no files matching './OpenNI2/Drivers/lib**.dylib'
```

It seems related?

**Comment by jonbinney** [comment]
@wjwwood do you see this in devel space, or only install space?

**Comment by wjwwood** [comment]
This was the devel space, I'm not convinced that it is related anymore.

**Comment by wjwwood** [comment]
Nope, this is definitely the bug mentioned in https://github.com/hcw70/OpenNI2/issues/12

**Comment by wjwwood** [comment]
It will happen in devel space and install space because it the bug is in openni2.

**Comment by wjwwood** [comment]
For instance if you launch from the folder where `OpenNI2/Drivers/...` is located, it works.

**Comment by wjwwood** [comment]
I can get it going with this environment variable:

```
OPENNI2_DRIVERS_PATH=/usr/local/Cellar/openni2/2.1.0.4/lib/OpenNI2/Drivers roslaunch openni2_launch openni2.launch
```

**Comment by jonbinney** [comment]
I only had the problem https://github.com/hcw70/OpenNI2/issues/12 when in install space. In devel space, catkin was getting the correct library path from openni2's pkgconfig info. Then it was adding `OpenNI2/Drivers/...` to LD_LIBRARY_PATH, so things worked for me (on ubuntu 12.04)

If you look in the CMakeLists.txt for openni2_camera, it tries to get the library directory for Openni2 from pkgconfig: https://github.com/ros-drivers/openni2_camera/blob/groovy-devel/CMakeLists.txt#L9

**Comment by mikeferguson** [comment]
I posted in https://github.com/hcw70/OpenNI2/issues/12, but I figured I would also post here:

I've been messing around with this today and have a patch that will fix this, by backporting a patch that was made to libopenni's linux xn shared library loader after our branch was made.

@jspricke I presume ROS is using your PPA for the deb, is that right? If so, where are you building your source deb out of, and where should I submit patches for libopenni?

**Comment by jspricke** [comment]
I've just pushed new source debs, should be in the PPA soon.

**Comment by mikeferguson** [comment]
@jspricke thanks!

**Comment by mikeferguson** [comment]
@tfoote How do we go about getting the updated libopenni2 debians onto packages.ros.org?

**Comment by tfoote** [comment]
I run a script to import from @jspricke 's PPA. What version do I need to make sure gets imported?

**Comment by jspricke** [comment]
- Tully Foote notifications@github.com [2013-08-21 10:17]:
  > I run a script to import from @jspricke 's PPA. What version do I need to make sure gets imported?

2.1.0.4-1~ppa2~*

**Comment by mikeferguson** [comment]
Deb is now updated, thanks @tfoote

**Comment by mikeferguson** [comment]
Tested new openni2_camera debs in ros-shadow-fixed -- all looks good.

**Comment by mikeferguson** [comment]
@wjwwood If there is still any issue on macOSX, let's get a separate ticket going for that.

**Comment by wjwwood** [comment]
I think it is working, but I will open a new ticket if needed.
