### ISSUE TITLE
Openni2  latest asus firmware version support

### ISSUE THREAD

**Issue by antondim** [ros-drivers/openni2_camera#108]
Hello, using lsusb , I can see that my Asus Primesense's firmware version is 0.01 (very old).

Q1 : First of all, is this really the firmware version ( bcdDevice property )

Q2: If yes, which is the latest firmware version that I could upgrade to and will not have problem with "openni2.launch" ? 

Reason for firmware upgrade: 
- Everything is working smoothly but there is an offset in pointcloud which is getting bigger. The further you go , the bigger the offset gets. Tried both default calibration .yaml files and custom ones that were exported through camera_calibration package. Maybe the firmware update, could fix this.

How I check the offset: 
- Laser data are getting compared visually with camera's pointcloud data

Thank you

**Comment by 130s** [comment]
@antondim Thanks for asking.

This repo hosts a OpenNI2 wrapper software for ROS, not OpenNI2 itself, which is https://github.com/OpenNI/OpenNI2. Your question <s>doesn't</s> appears to be more about OpenNI2 itself? If that's correct then I'd encourage you to ask in the upstream.

That said, firmware 0.01 sounds very old indeed. And for `openni2.launch`, which is a config file for the executable in the ROS wrapper, I guess the wrapper is meant to be agnostic to the firmware version as much as possible.

Closing for now. Feel free to continue posting ROS wrapper question.
