### ISSUE TITLE
Release into groovy and hydro

### ISSUE THREAD

**Issue by jonbinney** [ros-drivers/openni2_camera#11]
Currently blocked by https://github.com/ros-drivers/openni2_camera/issues/10

**Comment by Rouno** [comment]
Dear Jon, here is something I found interesting and that might help you : http://computervisionblog.wordpress.com/2013/06/09/hands-on-capri-building-an-openni2-ros-interface/

This guy managed to have a capri sensor (new tiny kinect) and set openni 2 up in ros.

Best regards

**Comment by jonbinney** [comment]
That's very cool. Good to know that openni2 will work with the capri

**Comment by Rouno** [comment]
Does it give you clues regarding your library linking troubles ?

**Comment by jonbinney** [comment]
No; we don't have a problem at build time, we have a problem with dynamically loading libraries with dlopen at runtime. So changing things in cmake won't help us.

**Comment by Rouno** [comment]
Hi Jon, I have a xtion pro live and I was wondering if openni 2 driver for ROS will support the sensor's stereo microphone ? And if yes, what kind of format could it be.

Regards

**Comment by hcw70** [comment]
@Rouno The Xtion audio interface is recognized under Ubuntu as a standard USB audio device and can be used as USB microphone out of the box.

**Comment by mikeferguson** [comment]
@jonbinney Do you have time to release this, or should I? I can do it later today if your OK with that.

**Comment by jonbinney** [comment]
@mikeferguson - go ahead and release it. Do you have the permissions you need?

**Comment by mikeferguson** [comment]
@jonbinney Yep, I have permissions here and in ros-gbp. Release incoming shortly.

**Comment by jonbinney** [comment]
@mikeferguson are you using the openni2_launch package?

**Comment by mikeferguson** [comment]
I have been using it for testing, but I think we want to move to rgbd_launch, correct? In which case I will avoid releasing openni2_launch.

**Comment by jonbinney** [comment]
Yeah, that's why i asked. There's still a need for an openni2_launch package, but it should just be a thin wrapper around rgbd_launch, much like what @piyushk did for the openni_launch package: https://github.com/ros-drivers/openni_launch/blob/hydro-devel/launch/openni.launch

It will be a while before I get around to that (i don't have an xtion right now), but if you wanted to take a crack at it... :-P

**Comment by mikeferguson** [comment]
Released... I'll close this tickets once the debs make it into public in a few days.

**Comment by mikeferguson** [comment]
Hydro debs are built and working, groovy are still in the queue, but I see no reason they won't work.

**Comment by jonbinney** [comment]
Thanks @mikeferguson !
