### ISSUE TITLE
Save a 3dpointcloud taken from Kinect 360 camera with rtabamp_ros 

### ISSUE THREAD

**Issue by karishmathumu** [ros-drivers/openni2_camera#110]
I need to save a entire 3d pointcloud and have a format or way to be able to export it onto Cloudcompare or Meshlab.
I am using rtabmap_ros and a turtlebot2 with a Kinect camera.

I have a rosbag file which is saved version of the 3d mapping with the rtabmap_ros. I could visualise the pointcloud on RVIZ and RTABVIZ, but I am not sure how to save this pointcloud as a whole and be able to view and export it on to cloudcompare or meshlab applications.

A. On RTABMAPVIZ (does not work for me) " The option in RTABMAPVIZ with File->Export 3D Cloud" doesnot work for me, because all the options on RTABMAPVIZ seem to be disabled, though I have first selected "download all the clouds" option under Edit menu on thr RTabmapviz application.

And

B. I am saving a rosbag file and playing it with the goal to save the pointcloud with pcl_ros package. But all I could save is a set of multiple pcd files (kind of image files), which when viewed with pcl_viewer, looks like an image outline ( made of red dots) of a map , where as the actual pointcloud saving and viewing is the goal. Kindly please help me.

--On terminal (also does not work) rosrun pcl_ros pointcloud_to_pcd input:=/rtabmap/cloud_map and changing the boolean value to true
--All i could get are a red dotted outline on the ground view.

Kindly please help me out. I am on the verge of completing my project. This is one last thing to be done.

Enclosed are the screenshots for your reference.

Thank you very much,

Karishma.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/71717377/123985873-1b515880-d9c6-11eb-990b-631c05b69996.png)
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/71717377/123985893-21dfd000-d9c6-11eb-8281-1c883f6f9111.png)
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/71717377/123985900-2310fd00-d9c6-11eb-8713-a096d7034f36.png)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/71717377/123985904-2310fd00-d9c6-11eb-9d98-6fe2df4896bf.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/71717377/123985905-23a99380-d9c6-11eb-89fe-2bb745a63108.png)

**Comment by mikeferguson** [comment]
As far as I can tell, this doesn't even really involve an openni2_camera issue - the correct place for this sort of thing is answers.ros.org - please post there.
