### ISSUE TITLE
Compiling error: error: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by jmguerreroh** [ros-drivers/openni2_camera#112]
After compiling using `colcon build --symlink-install` I obtain this error

```
/src/openni2_camera/openni2_camera/include/openni2_camera/openni2_device.h:69:37: error: ISO C++17 does not allow dynamic exception specifications
   69 |                 rclcpp::Node* node) throw (OpenNI2Exception);

```
Any idea?

**Comment by Juancams** [comment]
Removing all throw and OpenNI2Exception.

Check https://github.com/Juancams/openni2_camera

**Comment by 130s** [comment]
C++17 so I assume you're on ROS2 or something newer than what ROS1 supports. AFAIK the packages on this repo are not officially ported to ROS2, it's tracked in https://github.com/ros-drivers/openni2_camera/issues/90

**Comment by mikeferguson** [comment]
These exception thingies are gone in the ROS2 branch
