### ISSUE TITLE
Launching multiple devices by serial number sometimes fails

### ISSUE THREAD

**Issue by stwirth** [ros-drivers/openni2_camera#24]
When starting two instances of the driver together (e.g. from the same launch file) and both try to access all openni2 devices to request their serial number, one (or both) can (silently) fail. This makes resolving the device URI by serial number impossible (serial numbers for devices that could not be opened on startup are empty).

A possible solution might be to retry reading the serial numbers instead of doing it only once on startup.

**Comment by mikeferguson** [comment]
What type of devices are using? Do they normally return serial numbers? (I know certain firmware revisions do not return serial numbers at all).

**Comment by jonbinney** [comment]
Shortrange and longrange carmines. They normally return valid serial numbers; only fail sometimes if you launch two instances of the driver at the same time.
