### ISSUE TITLE
Release 0.2.4 for hydro?

### ISSUE THREAD

**Issue by awesomebytes** [ros-drivers/openni2_camera#32]
Would it be possible to release the last tag for hydro? (Please :P)

**Comment by mikeferguson** [comment]
@awesomebytes I do not have a 12.04 install to test hydro (and I know that the libopenni2 is different between the two) -- if you can test and confirm that 0.2.4 works on hydro, I will backport the additional changes to hydro and get an 0.1.5 release out.

**Comment by awesomebytes** [comment]
We use locally the version 0.2.4 (since yesterday) and it works like a charm.

**Comment by mikeferguson** [comment]
closing as Hydro is EOL -- we missed the window on this one.
