### ISSUE TITLE
Pending release

### ISSUE THREAD

**Issue by smits** [ros-drivers/openni2_camera#37]
Could someone release the latest version for indigo-devel?

**Comment by mikeferguson** [comment]
I'll get this out this weekend (next sync should be at least a week away)

**Comment by smits** [comment]
Thanks! FYI @b1willaert.

**Comment by smits** [comment]
Any news on this?

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/9654

**Comment by smits** [comment]
Thanks a lot!
