### ISSUE TITLE
openni2_driver_lib needs a dependency on GetSerial

### ISSUE THREAD

**Issue by tfoote** [ros-drivers/openni2_camera#43]
It's failing to build on Xenial 64 due to this: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__openni2_camera__ubuntu_xenial_amd64__binary/22/console

```
23:34:17 /usr/lib/ccache/x86_64-linux-gnu-g++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"openni2_camera\" -Dopenni2_driver_lib_EXPORTS -I/tmp/binarydeb/ros-kinetic-openni2-camera-0.2.6/obj-x86_64-linux-gnu/devel/include -I/tmp/binarydeb/ros-kinetic-openni2-camera-0.2.6/include -I/opt/ros/kinetic/include -I/usr/include/openni2  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC   -o CMakeFiles/openni2_driver_lib.dir/src/openni2_driver.cpp.o -c /tmp/binarydeb/ros-kinetic-openni2-camera-0.2.6/src/openni2_driver.cpp
23:34:21 In file included from /tmp/binarydeb/ros-kinetic-openni2-camera-0.2.6/src/openni2_driver.cpp:32:0:
23:34:21 /tmp/binarydeb/ros-kinetic-openni2-camera-0.2.6/include/openni2_camera/openni2_driver.h:54:38: fatal error: openni2_camera/GetSerial.h: No such file or directory
23:34:21 compilation terminated.
```

I believe [this line](https://github.com/ros-drivers/openni2_camera/blob/2dc246feb39f13a8e7f8b362dc1c5478abae668d/CMakeLists.txt#L54) needs the additional dependency `${PROJECT_NAME}_generate_messages_cpp`

Surprisingly this is the only platform where it is failing due to this race condition.

**Comment by jackieokay** [comment]
It would be if we could fix this ASAP (at least before the next Kinetic sync) since currently neither openni2_camera nor freenect_stack are available for Kinetic. @130s

**Comment by mikeferguson** [comment]
@jacquelinekay  -- if you can open a PR I can get it merged release -- but I don't have compile/test capabilities at the moment

**Comment by jackieokay** [comment]
I think #44 will fix this.

**Comment by jackieokay** [comment]
I think the build is still failing because the fixed version needs a release.

**Comment by mikeferguson** [comment]
@jacquelinekay I never saw a "build has returned to normal" on the deb, so I forgot to release -- I see http://build.ros.org/job/Kdev__openni2_camera__ubuntu_xenial_amd64/changes -- releasing now

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/11768
