### ISSUE TITLE
Lunar Release 

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-drivers/openni2_camera#49]
Howdy openni2_camera maintainers!

It would be really awesome to have a Lunar release of this very widely used package.
Thanks!

**Comment by mikaelarguedas** [comment]
Howdy @mikeferguson, any update on this ? it would be really great to have openni2 drivers in Lunar :smile:

**Comment by 130s** [comment]
@mikeferguson @ros-drivers/openni @wjwwood I can help release stuff if that helps, same as I do for  many other repos. If that sounds good one of you please add me write access here, possible `openni2_launch` and `*-release` repos. Thx.

**Comment by 130s** [comment]
> write access

Looks like I've already have one for all necessary repos. I'll take care of these.

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/15795 done

**Comment by mikaelarguedas** [comment]
thanks @130s !

**Comment by 130s** [comment]
Version 0.2.8 also made into Indigo https://github.com/ros/rosdistro/pull/15796
Kinetic https://github.com/ros/rosdistro/pull/15797
