### ISSUE TITLE
`device_id` arg ignores device id?

### ISSUE THREAD

**Issue by 130s** [ros-drivers/openni2_camera#73]
<a href="https://github.com/130s"><img src="https://avatars0.githubusercontent.com/u/1840401?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [130s](https://github.com/130s)**
_Thursday Aug 31, 2017 at 19:02 GMT_
_Originally opened as https://github.com/ros-drivers/openni2_launch/issues/38_

----

I need to confirm by myself but I have a feeling as per subject, e.g. with an input `device_id:=5@1`, only "5" is taken as the bus number and "1" is ignored.

**Comment by mikeferguson** [comment]
Not confirmed after 7 years = ticket closing time
