### ISSUE TITLE
Support occipital (structure.io) sensor?

### ISSUE THREAD

**Issue by xoxota99** [ros-drivers/openni2_camera#82]
Will this driver work with the structure.io sensor (which also uses OpenNI2)? I'm currently using https://github.com/fangchangma/openni2_ros_wrapper , but would love to get the additional color and raw depth sensor messages that this driver offers...

**Comment by 130s** [comment]
Thanks for the interest. Since you can probably get better response for a question like this at ROS question forum, please ask there https://answers.ros.org/questions/. Closing.
