### ISSUE TITLE
rgb_camera info and depth_camera info are the same?!

### ISSUE THREAD

**Issue by CesMak** [ros-drivers/openni2_camera#83]
If I 
```

 <include file="$(find openni2_launch)/launch/openni2.launch">
 <arg name="rgb_camera_info_url"
      value="file:///home/mlampre/.ros/camera_info/rgb_PS1080_PrimeSense.yaml" />
 <arg name="depth_camera_info_url"
      value="file:///home/mlampre/.ros/camera_info/depth_PS1080_PrimeSense.yaml" />
</include>
```

and have seperate .yaml files openni2 publishes the exact same messages on these topics:
camera/rgb/camera_info
camera/depth/camera_info

**Comment by 130s** [comment]
Thanks for the interest. Since you can probably get better response for a question like this at ROS question forum, please ask there https://answers.ros.org/questions/. Closing.
