### ISSUE TITLE
using openni2_launch with kinect box 360 

### ISSUE THREAD

**Issue by amalgmar12** [ros-drivers/openni2_camera#86]
Hi,
I used  kinect with openni_launch and everything works fine. However , I installed openni2 and libreenect , and I followed the tutorial but , It show me "no device" as bellow . I will be so grateful if you help me to find a solution .Thanks for advance :+1: 
os: Elementary os
ros version : Kinetic 
![openni2](https://user-images.githubusercontent.com/37368595/42423698-ab79e3fc-82f6-11e8-9b53-e75e26633731.png)

**Comment by 130s** [comment]
Thanks for the interest. Since you can probably get better response for a question like this at ROS question forum, please ask there https://answers.ros.org/questions/. Closing.
