### ISSUE TITLE
Required arguments id_manufacturer, id_product not set in openni2_tf_prefix.launch

### ISSUE THREAD

**Issue by tlind** [ros-drivers/openni2_camera#88]
Commit ff647b83d86c introduced a regression because `openni2_tf_prefix.launch` was not updated with the arguments `id_manufacturer` and `id_product`, which are since then required by `device.launch.xml`. Instead, `openni2.launch` was modified appropriately.

This means that currently `openni2_tf_prefix.launch` cannot be used if `load_driver` is true.

**Comment by 130s** [comment]
Thanks for the report. Do you think you can open a pull request?
(I'm the one who made the referenced commit but it might take at least a few days for me to get to it).

**Comment by 130s** [comment]
@tlind Please let me know if you're planning to provide a fix. Otherwise I'll try to squeeze my time into this later this week, as this is bad.

**Comment by tlind** [comment]
I unfortunately won't have the chance to submit a pull request within the next few days.

**Comment by 130s** [comment]
Opened PR https://github.com/ros-drivers/openni2_camera/pull/89
