### ISSUE TITLE
Support for Kinect?

### ISSUE THREAD

**Issue by danepowell** [ros-drivers/openni2_camera#9]
I'm wondering if anyone has openni2_camera or openni2_launch working with Kinect?

My understanding is that this would only be possible by using the freenect driver and OpenNI2-Freenect wrapper (https://github.com/piedar/OpenNI2-FreenectDriver), since there is no official OpenNI2-compatible driver for Linux. For OpenNI version 1.5, you could use the avin2 SensorKinect driver (https://github.com/avin2/SensorKinect), but I don't think that works with OpenNI2.

So, I'm running OpenNI2-Freenect, and when I try to roslaunch openni2.launch, I get a bunch of errors about unsupported IR/color/depth modes- I'm guessing because the freenect driver is limited in what modes it supports.

Can anyone clarify the situation for me? Am I right in these assumptions?

**Comment by jonbinney** [comment]
Right, the OpenNI2 library does not support the kinect right now, as far as I know.  The Openni2-freenect project you linked to looked promising, but i don't have any experience with it.

You could just use the ROS freenect driver directly: https://github.com/ros-drivers/freenect_stack
That should let you get ROS messages from your kinect. Is there some raoson you need to use OpenNI2?

**Comment by danepowell** [comment]
Thanks for clarifying- it might be worth noting in the README or project page that OpenNI2 doesn't support Kinect, and users should stick with OpenNI or freenect (although the OpenNI software is hard to come by now).

At any rate- I did switch to the freenect stack and it's working great. Thanks!

**Comment by jonbinney** [comment]
Good point, i've added a note in the readme pointing people to the freenect stack for kinects.
